const AUTO_GT_FINAL_FILE = {
  "ok": true,
  "type": "AutoGT Pro Final File",
  "jobId": "jmu21gkn8n",
  "productName": "【GS】1-ตู้เสื้อผ้าเด็กขนาด 70-90 ซม. แบบพับได้ ตู้เก็บของเด็ก ตู้เด็กหลายชั้น ราวแขวนเสื้อผ้าเด็ก. วัสดุพลาสติก กันฝุ่น พับเก็บได้ รุ่นหนาพิเศษ วัสดุหนา ไม้แขวนเสื้อ ราวตากผ้า คอนโด หอพัก",
  "productId": "1732527267337372979",
  "productID": "1732527267337372979",
  "platform": "tiktok",
  "sourceUrl": "https://www.tiktok.com/view/product/1732527267337372979",
  "sceneCount": 2,
  "trimSeconds": 0,
  "rule": "clip 1 full length; clip 2+ trim first 1 second before concat",
  "finalFile": "C:\\Users\\Blue\\Downloads\\AutoGT Tiktok File\\1732527267337372979-【GS】1-ตู้เสื้อผ้าเด็กขนาด 70-90 ซม. แบบพับได้ ตู้เก็บของเด็ก ตู้เด็กหลายชั้น ราว.mp4",
  "finalUrl": "/library-file/1732527267337372979-%E3%80%90GS%E3%80%911-%E0%B8%95%E0%B8%B9%E0%B9%89%E0%B9%80%E0%B8%AA%E0%B8%B7%E0%B9%89%E0%B8%AD%E0%B8%9C%E0%B9%89%E0%B8%B2%E0%B9%80%E0%B8%94%E0%B9%87%E0%B8%81%E0%B8%82%E0%B8%99%E0%B8%B2%E0%B8%94%2070-90%20%E0%B8%8B%E0%B8%A1.%20%E0%B9%81%E0%B8%9A%E0%B8%9A%E0%B8%9E%E0%B8%B1%E0%B8%9A%E0%B9%84%E0%B8%94%E0%B9%89%20%E0%B8%95%E0%B8%B9%E0%B9%89%E0%B9%80%E0%B8%81%E0%B9%87%E0%B8%9A%E0%B8%82%E0%B8%AD%E0%B8%87%E0%B9%80%E0%B8%94%E0%B9%87%E0%B8%81%20%E0%B8%95%E0%B8%B9%E0%B9%89%E0%B9%80%E0%B8%94%E0%B9%87%E0%B8%81%E0%B8%AB%E0%B8%A5%E0%B8%B2%E0%B8%A2%E0%B8%8A%E0%B8%B1%E0%B9%89%E0%B8%99%20%E0%B8%A3%E0%B8%B2%E0%B8%A7.mp4",
  "videoFileName": "1732527267337372979-【GS】1-ตู้เสื้อผ้าเด็กขนาด 70-90 ซม. แบบพับได้ ตู้เก็บของเด็ก ตู้เด็กหลายชั้น ราว.mp4",
  "createdAt": "2026-09-15T02:27:59.864Z",
  "clips": [
    {
      "scene": 1,
      "source": "https://flow-content.google/video/1519e5dd-1640-4ef8-80c7-9068d436260b?Expires=1789460671&KeyName=labs-flow-prod-cdn-key&Signature=3dLZaiu2UTnuvN6NNo5wwiWkF9A",
      "trimSeconds": 0,
      "rule": "keep full clip"
    },
    {
      "scene": 2,
      "source": "https://flow-content.google/video/bfa697fb-3c34-4ab5-af17-e8c471fcc88b?Expires=1789460814&KeyName=labs-flow-prod-cdn-key&Signature=ql08gXEWeeawYVqnbtn1x7-xza0",
      "trimSeconds": 0,
      "rule": "trim first second before concat"
    }
  ],
  "promptLog": {
    "defaultBehavior": "Prompt ปัจจุบันเป็นค่าเริ่มต้น และข้อความรายฉากจะแทนส่วนคำสั่งฉากโดยคงข้อมูลสินค้า บทพูด และข้อห้ามของระบบไว้",
    "mandatoryPrompt": "ข้อห้าม: มนุษย์มี 2 มือห้ามเพิ่มอวัยวะดูดีๆ, สินค้าห้ามเปลี่ยนขนาด ใช้ขนาดจริง, ตัวละครต้องเป็นผู้ใหญ่ (อายุ 18 ปีขึ้นไป) เท่านั้น — ห้ามมีเด็ก ทารก หรือผู้เยาว์ในภาพและวิดีโอเด็ดขาด | ห้ามอ้างสรรพคุณทางการแพทย์ หรือการันตีผลลัพธ์ | ห้ามสร้างราคา ส่วนลด หรือโปรโมชันที่ไม่มีจริง และห้ามพูดตัวเลขราคา | ห้ามอ้างข้อมูลที่ยืนยันไม่ได้ (อันดับ 1, ขายดีที่สุด, ของแท้ 100%, ส่งฟรี) | ห้ามใส่โลโก้ ข้อความ หรือลายน้ำของแพลตฟอร์มอื่นในภาพ",
    "promptSets": {
      "textRulesPrompt": "",
      "speechRulesPrompt": "",
      "extraPrompt": "",
      "imageContentPrompt": "",
      "imageMandatoryPrompt": ""
    },
    "scenePromptInputs": [
      "Cinematic photorealistic video. Adult female creator in a bright modern room presenting - at true physical scale without revealing the product name. If - is furniture/cabinet, she stands beside the full-size item placed on the floor. If small, she holds it naturally in her hands. Eye-level medium shot. She smiles warmly and speaks naturally at a calm, slow, and relaxed conversational pace in Thai: \"{{บทพูดฉาก 1}}\". Realistic human hands (exactly two hands), natural movements, no miniature furniture, no cartoons, no children, no subtitles. Any on-screen text must remain completely static, sharp, legible, and persistent throughout the clip without fading or distorting.",
      "Cinematic photorealistic video, seamless continuation from Scene 1. Same adult female creator in the exact same bright room and outfit. Medium close-up shot focused on her actively using or touching - at true physical scale. She looks directly into the camera, smiling with confident yet steady, unhurried, natural pacing, reveals the product name, and speaks in Thai: \"{{บทพูดฉาก 2}}\". Realistic hands, natural gestures, no miniature props, no cartoons, no children, no subtitles. Any on-screen text must stay completely static, sharp, and visible until the video ends."
    ],
    "defaultVideoPrompts": [
      "Scene 1/2 — BASE SCENE\nเปิดเรื่องให้ชัดเจน และล็อกตัวละคร ใบหน้า เสียง สินค้า เสื้อผ้า ฉาก แสง และมุมกล้องนี้ไว้สำหรับฉากถัดไป\nคลิปวิดีโอแนวตั้ง 9:16 ความยาว 8 วินาที สำหรับโปรโมทสินค้าบน TikTok/Shopee\nกล้องเคลื่อนนุ่มนวลต่อเนื่องไม่กระตุก โฟกัสที่สินค้าเป็นหลัก ไม่ตัดสลับฉากหลายครั้ง\nสินค้าต้องคงรูปร่าง สี บรรจุภัณฑ์ โลโก้ และข้อความเดิมตลอดคลิป\nถ้าในภาพมีข้อความปรากฏอยู่ (เช่น หัวข้อโปรโมชั่นหรือป้ายราคา) ข้อความนั้นต้องอยู่นิ่ง ชัดเจน อ่านออก และคงอยู่ตลอดทั้งคลิปจนจบวิดีโอ ห้ามข้อความเลือนหาย บิดเบี้ยว หรือหายไปกลางคลิปเด็ดขาด\nชื่อสินค้า: 【GS】1-ตู้เสื้อผ้าเด็กขนาด 70-90 ซม. แบบพับได้ ตู้เก็บของเด็ก ตู้เด็กหลายชั้น ราวแขวนเสื้อผ้าเด็ก. วัสดุพลาสติก กันฝุ่น พับเก็บได้ รุ่นหนาพิเศษ วัสดุหนา ไม้แขวนเสื้อ ราวตากผ้า คอนโด หอพัก\nบทพูดภาษาไทย 20-28 คำ พูดจบพอดีใน 8 วินาที\nต้องเอ่ยชื่อสินค้าอย่างน้อย 1 ครั้ง\nพูดเหมือนคนจริงที่ใช้สินค้าแล้วอยากบอกต่อ ไม่ใช่พรีเซนเตอร์อ่านสคริปต์ — ใช้ภาษาพูดจริงของคนไทย\nเน้นความรู้สึก 1 อย่างที่ใช้แล้วรู้สึกได้ ไม่ต้องไล่ลิสต์คุณสมบัติ\nปิดท้ายให้คนดูอยากซื้อ พูดมั่นใจมีพลัง ห้ามจบเบาๆ แบบ \"ลองดูนะ\"\nห้ามพูดตัวเลขราคาหรือส่วนลด\nข้อห้าม: มนุษย์มี 2 มือห้ามเพิ่มอวัยวะดูดีๆ, สินค้าห้ามเปลี่ยนขนาด ใช้ขนาดจริง, ตัวละครต้องเป็นผู้ใหญ่ (อายุ 18 ปีขึ้นไป) เท่านั้น — ห้ามมีเด็ก ทารก หรือผู้เยาว์ในภาพและวิดีโอเด็ดขาด | ห้ามอ้างสรรพคุณทางการแพทย์ หรือการันตีผลลัพธ์ | ห้ามสร้างราคา ส่วนลด หรือโปรโมชันที่ไม่มีจริง และห้ามพูดตัวเลขราคา | ห้ามอ้างข้อมูลที่ยืนยันไม่ได้ (อันดับ 1, ขายดีที่สุด, ของแท้ 100%, ส่งฟรี) | ห้ามใส่โลโก้ ข้อความ หรือลายน้ำของแพลตฟอร์มอื่นในภาพ",
      "Scene 2/2 — CONTINUOUS EXTENDED SCENE\nต่อเนื่องจากเฟรมสุดท้ายของคลิปก่อนหน้าทันที โดยคงตัวละคร ใบหน้า เสียง สินค้า เสื้อผ้า ฉาก แสง และมุมกล้องเดิม\nคลิปวิดีโอแนวตั้ง 9:16 ความยาว 8 วินาที สำหรับโปรโมทสินค้าบน TikTok/Shopee\nกล้องเคลื่อนนุ่มนวลต่อเนื่องไม่กระตุก โฟกัสที่สินค้าเป็นหลัก ไม่ตัดสลับฉากหลายครั้ง\nสินค้าต้องคงรูปร่าง สี บรรจุภัณฑ์ โลโก้ และข้อความเดิมตลอดคลิป\nถ้าในภาพมีข้อความปรากฏอยู่ (เช่น หัวข้อโปรโมชั่นหรือป้ายราคา) ข้อความนั้นต้องอยู่นิ่ง ชัดเจน อ่านออก และคงอยู่ตลอดทั้งคลิปจนจบวิดีโอ ห้ามข้อความเลือนหาย บิดเบี้ยว หรือหายไปกลางคลิปเด็ดขาด\nชื่อสินค้า: 【GS】1-ตู้เสื้อผ้าเด็กขนาด 70-90 ซม. แบบพับได้ ตู้เก็บของเด็ก ตู้เด็กหลายชั้น ราวแขวนเสื้อผ้าเด็ก. วัสดุพลาสติก กันฝุ่น พับเก็บได้ รุ่นหนาพิเศษ วัสดุหนา ไม้แขวนเสื้อ ราวตากผ้า คอนโด หอพัก\nบทพูดภาษาไทย 20-28 คำ พูดจบพอดีใน 8 วินาที\nต้องเอ่ยชื่อสินค้าอย่างน้อย 1 ครั้ง\nพูดเหมือนคนจริงที่ใช้สินค้าแล้วอยากบอกต่อ ไม่ใช่พรีเซนเตอร์อ่านสคริปต์ — ใช้ภาษาพูดจริงของคนไทย\nเน้นความรู้สึก 1 อย่างที่ใช้แล้วรู้สึกได้ ไม่ต้องไล่ลิสต์คุณสมบัติ\nปิดท้ายให้คนดูอยากซื้อ พูดมั่นใจมีพลัง ห้ามจบเบาๆ แบบ \"ลองดูนะ\"\nห้ามพูดตัวเลขราคาหรือส่วนลด\nข้อห้าม: มนุษย์มี 2 มือห้ามเพิ่มอวัยวะดูดีๆ, สินค้าห้ามเปลี่ยนขนาด ใช้ขนาดจริง, ตัวละครต้องเป็นผู้ใหญ่ (อายุ 18 ปีขึ้นไป) เท่านั้น — ห้ามมีเด็ก ทารก หรือผู้เยาว์ในภาพและวิดีโอเด็ดขาด | ห้ามอ้างสรรพคุณทางการแพทย์ หรือการันตีผลลัพธ์ | ห้ามสร้างราคา ส่วนลด หรือโปรโมชันที่ไม่มีจริง และห้ามพูดตัวเลขราคา | ห้ามอ้างข้อมูลที่ยืนยันไม่ได้ (อันดับ 1, ขายดีที่สุด, ของแท้ 100%, ส่งฟรี) | ห้ามใส่โลโก้ ข้อความ หรือลายน้ำของแพลตฟอร์มอื่นในภาพ"
    ],
    "videoPrompts": [
      "Scene 1/2 — BASE SCENE\nCinematic photorealistic video. Adult female creator in a bright modern room presenting - at true physical scale without revealing the product name. If - is furniture/cabinet, she stands beside the full-size item placed on the floor. If small, she holds it naturally in her hands. Eye-level medium shot. She smiles warmly and speaks naturally at a calm, slow, and relaxed conversational pace in Thai: \"{{บทพูดฉาก 1}}\". Realistic human hands (exactly two hands), natural movements, no miniature furniture, no cartoons, no children, no subtitles. Any on-screen text must remain completely static, sharp, legible, and persistent throughout the clip without fading or distorting.\nถ้าในภาพมีข้อความปรากฏอยู่ (เช่น หัวข้อโปรโมชั่นหรือป้ายราคา) ข้อความนั้นต้องอยู่นิ่ง ชัดเจน อ่านออก และคงอยู่ตลอดทั้งคลิปจนจบวิดีโอ ห้ามข้อความเลือนหาย บิดเบี้ยว หรือหายไปกลางคลิปเด็ดขาด\nชื่อสินค้า: 【GS】1-ตู้เสื้อผ้าเด็กขนาด 70-90 ซม. แบบพับได้ ตู้เก็บของเด็ก ตู้เด็กหลายชั้น ราวแขวนเสื้อผ้าเด็ก. วัสดุพลาสติก กันฝุ่น พับเก็บได้ รุ่นหนาพิเศษ วัสดุหนา ไม้แขวนเสื้อ ราวตากผ้า คอนโด หอพัก\nบทพูดภาษาไทย 20-28 คำ พูดจบพอดีใน 8 วินาที\nต้องเอ่ยชื่อสินค้าอย่างน้อย 1 ครั้ง\nพูดเหมือนคนจริงที่ใช้สินค้าแล้วอยากบอกต่อ ไม่ใช่พรีเซนเตอร์อ่านสคริปต์ — ใช้ภาษาพูดจริงของคนไทย\nเน้นความรู้สึก 1 อย่างที่ใช้แล้วรู้สึกได้ ไม่ต้องไล่ลิสต์คุณสมบัติ\nปิดท้ายให้คนดูอยากซื้อ พูดมั่นใจมีพลัง ห้ามจบเบาๆ แบบ \"ลองดูนะ\"\nห้ามพูดตัวเลขราคาหรือส่วนลด\nข้อห้าม: มนุษย์มี 2 มือห้ามเพิ่มอวัยวะดูดีๆ, สินค้าห้ามเปลี่ยนขนาด ใช้ขนาดจริง, ตัวละครต้องเป็นผู้ใหญ่ (อายุ 18 ปีขึ้นไป) เท่านั้น — ห้ามมีเด็ก ทารก หรือผู้เยาว์ในภาพและวิดีโอเด็ดขาด | ห้ามอ้างสรรพคุณทางการแพทย์ หรือการันตีผลลัพธ์ | ห้ามสร้างราคา ส่วนลด หรือโปรโมชันที่ไม่มีจริง และห้ามพูดตัวเลขราคา | ห้ามอ้างข้อมูลที่ยืนยันไม่ได้ (อันดับ 1, ขายดีที่สุด, ของแท้ 100%, ส่งฟรี) | ห้ามใส่โลโก้ ข้อความ หรือลายน้ำของแพลตฟอร์มอื่นในภาพ",
      "Scene 2/2 — CONTINUOUS EXTENDED SCENE\nCinematic photorealistic video, seamless continuation from Scene 1. Same adult female creator in the exact same bright room and outfit. Medium close-up shot focused on her actively using or touching - at true physical scale. She looks directly into the camera, smiling with confident yet steady, unhurried, natural pacing, reveals the product name, and speaks in Thai: \"{{บทพูดฉาก 2}}\". Realistic hands, natural gestures, no miniature props, no cartoons, no children, no subtitles. Any on-screen text must stay completely static, sharp, and visible until the video ends.\nถ้าในภาพมีข้อความปรากฏอยู่ (เช่น หัวข้อโปรโมชั่นหรือป้ายราคา) ข้อความนั้นต้องอยู่นิ่ง ชัดเจน อ่านออก และคงอยู่ตลอดทั้งคลิปจนจบวิดีโอ ห้ามข้อความเลือนหาย บิดเบี้ยว หรือหายไปกลางคลิปเด็ดขาด\nชื่อสินค้า: 【GS】1-ตู้เสื้อผ้าเด็กขนาด 70-90 ซม. แบบพับได้ ตู้เก็บของเด็ก ตู้เด็กหลายชั้น ราวแขวนเสื้อผ้าเด็ก. วัสดุพลาสติก กันฝุ่น พับเก็บได้ รุ่นหนาพิเศษ วัสดุหนา ไม้แขวนเสื้อ ราวตากผ้า คอนโด หอพัก\nบทพูดภาษาไทย 20-28 คำ พูดจบพอดีใน 8 วินาที\nต้องเอ่ยชื่อสินค้าอย่างน้อย 1 ครั้ง\nพูดเหมือนคนจริงที่ใช้สินค้าแล้วอยากบอกต่อ ไม่ใช่พรีเซนเตอร์อ่านสคริปต์ — ใช้ภาษาพูดจริงของคนไทย\nเน้นความรู้สึก 1 อย่างที่ใช้แล้วรู้สึกได้ ไม่ต้องไล่ลิสต์คุณสมบัติ\nปิดท้ายให้คนดูอยากซื้อ พูดมั่นใจมีพลัง ห้ามจบเบาๆ แบบ \"ลองดูนะ\"\nห้ามพูดตัวเลขราคาหรือส่วนลด\nข้อห้าม: มนุษย์มี 2 มือห้ามเพิ่มอวัยวะดูดีๆ, สินค้าห้ามเปลี่ยนขนาด ใช้ขนาดจริง, ตัวละครต้องเป็นผู้ใหญ่ (อายุ 18 ปีขึ้นไป) เท่านั้น — ห้ามมีเด็ก ทารก หรือผู้เยาว์ในภาพและวิดีโอเด็ดขาด | ห้ามอ้างสรรพคุณทางการแพทย์ หรือการันตีผลลัพธ์ | ห้ามสร้างราคา ส่วนลด หรือโปรโมชันที่ไม่มีจริง และห้ามพูดตัวเลขราคา | ห้ามอ้างข้อมูลที่ยืนยันไม่ได้ (อันดับ 1, ขายดีที่สุด, ของแท้ 100%, ส่งฟรี) | ห้ามใส่โลโก้ ข้อความ หรือลายน้ำของแพลตฟอร์มอื่นในภาพ"
    ]
  },
  "caption": "【GS】1-ตู้เสื้อผ้าเด็กขนาด 70-90 ซม. แบบพับได้ ตู้เก็บของเด็ก ตู้เด็กหลายชั้น ราวแขวนเสื้อผ้าเด็ก. วัสดุพลาสติก กันฝุ่น พับเก็บได้ รุ่นหนาพิเศษ วัสดุหนา ไม้แขวนเสื้อ ราวตากผ้า คอนโด หอพัก"
};
if (typeof window !== "undefined") window.AUTO_GT_FINAL_FILE = AUTO_GT_FINAL_FILE;
if (typeof module !== "undefined") module.exports = AUTO_GT_FINAL_FILE;
